# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.11
repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v3.2.0
  #   hooks:
  #     - id: check-yaml
  #       exclude: ^.gitlab-ci.yml
  #     - id: check-added-large-files
  #     - id: end-of-file-fixer
  #     - id: trailing-whitespace
  #     - id: check-toml
  #     - id: pretty-format-json
  #       args:
  #         - "--no-sort-keys"
  #         - "--autofix"
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  #       name: isort
  #       args: ["--profile", "black"]
  # - repo: https://github.com/psf/black
  #   rev: 22.6.0
  #   hooks:
  #     - id: black
  #       args:
  #         - "-l 120"
  # -   repo: https://github.com/asottile/blacken-docs
  #     rev: v1.12.1
  #     hooks:
  #     -   id: blacken-docs
  #         additional_dependencies: [black==22.6.0]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: update-chromedriver-version
        name: Update ChromeDriver Version
        entry: bash update_chromedriver_version.sh
        language: system
        files: poetry.Dockerfile
