default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: poetry-pytest
        name: Poetry Pytest
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
      - id: update-chromedriver-version
        name: Update ChromeDriver Version
        entry: python .github/hooks/update-chromedriver.py
        language: system
        pass_filenames: false
        args:
          - poetry.Dockerfile
      - id: runner-generator
        name: Runner Generator
        entry: python .github/hooks/runner-generator.py
        language: system
        types: [file]