name: 🤖 BookerBot — Auto-run @{time}

on:
  schedule:
    - cron: "{cron}" # “At {cron_hour}:{cron_minute:02d} UTC every day.”
  workflow_dispatch:

jobs:
  call-octivbooker:
    uses: seblum/octiv-booker/.github/workflows/callable-runner.yaml@master
    secrets:
      OCTIV_USERNAME: ${{{{ secrets.OCTIV_USERNAME }}}}
      OCTIV_PASSWORD: ${{{{ secrets.OCTIV_PASSWORD }}}}
      EMAIL_SENDER: ${{{{ secrets.EMAIL_SENDER }}}}
      EMAIL_PASSWORD: ${{{{ secrets.EMAIL_PASSWORD }}}}
      EMAIL_RECEIVER: ${{{{ secrets.EMAIL_RECEIVER }}}}
      EMAIL_RECEIVER_NAME: ${{{{ secrets.EMAIL_RECEIVER_NAME }}}}
    with:
      docker_image: octivbooker:vv2.8.0
      time: "{time}"
