name: 🤖 Octiv BookerBot — Auto-run @ {time}

on:
  schedule:
    - cron: "{cron}" # “At {cron_hour}:{cron_minute:02d} UTC every day.”
  workflow_dispatch:
  push:

jobs:
  call-octivbooker:
    uses: seblum/octiv-booker/.github/workflows/runner-callable.yaml@ghactions-setup
    secrets:
      OCTIV_USERNAME: ${{{{ secrets.OCTIV_USERNAME }}}}
      OCTIV_PASSWORD: ${{{{ secrets.OCTIV_PASSWORD }}}}
      EMAIL_SENDER: ${{{{ secrets.EMAIL_SENDER }}}}
      EMAIL_PASSWORD: ${{{{ secrets.EMAIL_PASSWORD }}}}
      EMAIL_RECEIVER: ${{{{ secrets.EMAIL_RECEIVER }}}}
      EMAIL_RECEIVER_NAME: ${{{{ secrets.EMAIL_RECEIVER_NAME }}}}
    with:
      days_before_bookable: ${{{{ VARS.DAYS_BEFORE_BOOKABLE }}}}
      execution_booking_time: ${{{{ VARS.EXECUTION_BOOKING_TIME }}}}
      docker_image: octivbooker:v2.6.3
      time: "{time}"
