chromedriver: '/usr/local/bin/chromedriver'
base_url: 'https://app.octivfitness.com/login'

# Hpw many days prior can I book: current 6
days_before_bookable: 6
# book class = True, cancel class = False
book_class: True

class_list:
  Monday: 
    - time: "19:00"
      class: "Remote Coaching"
    - time: "19:00"
      class: "Open Gym"
    - time: "20:30"
      class: "Open Gym"
  Tuesday:
    - time: "19:00"
      class: "Remote Coaching"
    - time: "19:00"
      class: "Open Gym"
    - time: "20:30"
      class: "Open Gym"
  Wednesday:
    - time: "19:00"
      class: "Remote Coaching"
    - time: "19:00"
      class: "Open Gym"
    - time: "20:30"
      class: "Open Gym"
  Thursday:
    - time: "19:00"
      class: "Remote Coaching"
    - time: "19:00"
      class: "Open Gym"
    - time: "20:30"
      class: "Open Gym"
  Friday:
    - time: "19:00"
      class: "Remote Coaching"
    - time: "19:00"
      class: "Open Gym"
    - time: "19:30"
      class: "CLASS"
      wl: False
  Saturday: 
    - time: None
      class: None
  Sunday:
    - time: "11:30"
      class: "Weightlifting"
