chromedriver: '/usr/local/bin/chromedriver'
base_url: 'https://app.octivfitness.com/login'

# Hpw many days prior can I book
days_before_bookable: 5
# book class = True, cancel class = False
book_class: True

class:
  Monday: "None"
  Tuesday: "None"
  Wednesday: "None"
  Thursday: "Weightlifting"
  Friday: "None"
  Saturday: "Gynmastics"
  Sunday: "Weightlifting"
