name: publish docker CD

env:
  DOCKERREPO: seblum/octivbooker
  TAG: test2 # v1.5.0


on:
  push:
    # branches: master
    # tags: v[12].[0-9]+.[0-9]+
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  docker:
    name: Build & Push octiverbooker:${{ matrix.directory }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: ["test1",${{ env.TAG }}]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./slotBooker/poetry.Dockerfile
          push: true
          tags: ${{ env.DOCKERREPO }}:${{ matrix.tags }}
          # context: .
