name: Create release notes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Create release
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag}" \
              --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        